package com.example.foodshot


class Calories() {
        var calories = mapOf(
                "Sushi" to 133,
                "Cheese" to 350,
                "Sandwich" to 280,
                "Hamburger" to 250,
                "Bell pepper" to 31,
                "Broccoli" to 34,
                "Salad" to 175,
                "Carrot" to 35,
                "Cabbage" to 25,
                "Zucchini" to 17,
                "Pumpkin" to 26,
                "Garden Asparagus" to 20,
                "Tomato" to 18,
                "Radish" to 16,
                "Cucumber" to 15,
                "Crab" to 84,
                "Shrimp" to 85,
                "Lobster" to 89,
                "Squid" to 92,
                "Pizza" to 266,
                "Pasta" to 131,
                "Mushroom" to 22,
                "Tart" to 298,
                "Croissant" to 406,
                "Doughnut" to 452,
                "Bread" to 265,
                "Cookie" to 500,
                "Muffin" to 340,
                "Egg (Food)" to 155,
                "Watermelon" to 30,
                "Pomegranate" to 83,
                "Pineapple" to 50,
                "Mango" to 60,
                "Apple" to 52,
                "Grape" to 67,
                "Pear" to 57,
                "Banana" to 89,
                "Hot dog" to 289,
                "French fries" to 312,
                "Waffle" to 291,
                "Popcorn" to 375,
                "Ice cream" to 207,
                "Candy" to 500,
                "Cake" to 450,
                "Strawberry" to 41,
                "Orange" to 43,
                "Lemon" to 34
        )
}
